spring:
  profiles:
    active: default
  config:
    import: application_prod.yaml
  application:
    name: memo-vocab-spring
  datasource:
    url: jdbc:postgresql://localhost:5432/memo-vocab-db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
#    open-in-view: false
  hibernate:
    ddl-auto: none
  flyway:
    enabled: false
    validate-on-migrate: true
    default-schema: memo-vocab
    locations: classpath:db/migration
  security:
    user:
      name: user
      password: password
  cache:
    type: redis
    cache-names: userCache
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      springframework:
        web: DEBUG
        validation: DEBUG
        security: DEBUG
