spring:
  application:
    name: memo-vocab-spring
  datasource:
    url: jdbc:postgresql://localhost:5432/memo-vocab-db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: none

  flyway:
    enabled: false
    validate-on-migrate: true
    default-schema: memo-vocab
    locations: classpath:db/migration