FROM flyway/flyway
COPY src/main/resources/db/migration /flyway/sql
# tag as ginying24/memo-vocab-flyway:latest and push to registry
# docker build -f kubectl/Dockerfile -t ginying24/memo-vocab-flyway:latest .
# docker push ginying24/memo-vocab-flyway:latest