services:
  network-deploy-service:
    networks:
      - memo-vocab-network

  microservice-config:
    extends:
      service: network-deploy-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
