spring:
  profiles:
    active: prod
  application:
    name: memo-vocab-spring
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/memo-vocab-db
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
#    open-in-view: false
  hibernate:
    ddl-auto: none
  flyway:
    enabled: false
    validate-on-migrate: true
    default-schema: memo-vocab
    locations: classpath:db/migration
  security:
    user:
      name: user
      password: password
  cache:
    type: redis
    cache-names: userCache
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cloud:
    stream:
      bindings:
        emailMessage-out-0:                   # output binding name
          destination: email-communication    # exchange name in RabbitMQ
        allNotificationMessage-out-0:
          destination: all-notification-communication

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
